theme: jekyll-theme-minimal
title: The Reafactored Road
description: Welcome to The Refactored Road — a journal of reflections, experiments, and stories from the crossroads of software architecture, agile thinking, and creative living.
